// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Viacheslav Shynkarenko

//! Stable diagnostic code registry.
//!
//! This module defines all diagnostic codes used by the Miri compiler.
//! Each code is assigned a permanent identifier in the format `MER_<AREA>_<NUM>`.
//!
//! ## Code Stability
//!
//! Codes are write-once and forever. A code is never re-used, even if the check
//! it corresponds to is removed. When a check is removed, its code is marked
//! `reserved` to prevent future re-use.
//!
//! ## Areas
//!
//! - LEX: Lexer (lexical analysis)
//! - PAR: Parser (syntax analysis)
//! - NAM: Naming and identifiers
//! - IMP: Imports and module loading
//! - TYP: Type checker (type inference and validation)
//! - OWN: Ownership and resource management
//! - MIR: MIR lowering (intermediate representation)
//! - CG: Code generation
//! - RT: Runtime traps and failures
//! - TAR: Target-specific capabilities and limits
//! - BLD: Build and command-invocation diagnostics

use crate::diagnostics::{FixSafety, Severity};
use std::str::FromStr;

// Macro-based code registry. This is the single source of truth for all diagnostic codes.
// Each tuple is: (AREA, NUM, VariantName, "Title", Severity, is_reserved)
macro_rules! diagnostics {
    ($($area:expr, $num:expr, $variant:ident, $title:expr, $severity:expr, $reserved:expr, $fix_safety:expr),* $(,)?) => {
        /// A stable diagnostic code assigned to a compiler check or error.
        ///
        /// Derives Clone, Copy, Debug, PartialEq, Eq, and Hash so codes can be stored
        /// in sets, used as map keys, and compared for equality without allocation.
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
        #[non_exhaustive]
        pub enum DiagnosticCode {
            $($variant),*
        }

        impl DiagnosticCode {
            /// Get the wire string representation (e.g., "MER_TYP_001").
            pub fn as_str(&self) -> &'static str {
                match self {
                    $(Self::$variant => concat!("MER_", $area, "_", $num)),*
                }
            }

            /// Get the title for this diagnostic code.
            pub fn title(&self) -> &'static str {
                match self {
                    $(Self::$variant => $title),*
                }
            }

            /// Get the area code (e.g., "LEX", "PAR").
            pub fn area(&self) -> &'static str {
                match self {
                    $(Self::$variant => $area),*
                }
            }

            /// Get the number within the area (e.g., "001", "042").
            pub fn number(&self) -> &'static str {
                match self {
                    $(Self::$variant => $num),*
                }
            }

            /// Get the severity level for this code.
            pub fn severity(&self) -> Severity {
                match self {
                    $(Self::$variant => $severity),*
                }
            }

            /// Check if this code is reserved (will not be re-assigned).
            pub fn is_reserved(&self) -> bool {
                match self {
                    $(Self::$variant => $reserved),*
                }
            }

            /// Get the fix-safety level for this code.
            pub fn fix_safety(&self) -> crate::diagnostics::FixSafety {
                match self {
                    $(Self::$variant => $fix_safety),*
                }
            }

            /// Return all diagnostic codes in stable order.
            pub fn all() -> &'static [DiagnosticCode] {
                &[
                    $(Self::$variant),*
                ]
            }

            /// Get the embedded documentation for this diagnostic code.
            pub fn doc(&self) -> &'static str {
                match self {
                    $(Self::$variant => include_str!(
                        concat!("../../docs/diagnostics/MER_", $area, "_", $num, ".md")
                    )),*
                }
            }

            /// Parse the embedded documentation into a structured explanation.
            pub fn explanation(&self) -> crate::diagnostics::Explanation {
                crate::diagnostics::Explanation::parse(*self, self.doc())
            }
        }

        impl std::fmt::Display for DiagnosticCode {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "{}", self.as_str())
            }
        }

        impl FromStr for DiagnosticCode {
            type Err = String;

            fn from_str(s: &str) -> Result<Self, Self::Err> {
                for code in Self::all() {
                    if code.as_str() == s {
                        return Ok(*code);
                    }
                }
                Err(format!("unknown diagnostic code: {}", s))
            }
        }

        // Compile-time uniqueness check via const evaluation.
        // Compares (area, num) pairs using byte-level comparison to ensure no duplicates.
        const _: () = {
            const fn bytes_equal(a: &[u8], b: &[u8]) -> bool {
                if a.len() != b.len() {
                    return false;
                }
                let mut i = 0;
                while i < a.len() {
                    if a[i] != b[i] {
                        return false;
                    }
                    i += 1;
                }
                true
            }

            const fn check_uniqueness() {
                // Each entry is the wire string (area_num pair encoded as bytes)
                const ENTRIES: &[(&str, &str)] = &[
                    $((stringify!($area), stringify!($num))),*
                ];

                let mut i = 0;
                while i < ENTRIES.len() {
                    let mut j = i + 1;
                    while j < ENTRIES.len() {
                        // Check if area and num both match
                        if bytes_equal(ENTRIES[i].0.as_bytes(), ENTRIES[j].0.as_bytes())
                            && bytes_equal(ENTRIES[i].1.as_bytes(), ENTRIES[j].1.as_bytes())
                        {
                            panic!("Duplicate diagnostic code");
                        }
                        j += 1;
                    }
                    i += 1;
                }
            }

            const _: () = { check_uniqueness(); };
        };
    };
}

// Invoke the macro with all diagnostic codes.
// Format: (AREA, NUM, VariantName, "Title", Severity, is_reserved, FixSafety)
diagnostics!(
    // LEX — Lexer (13 codes: 001-013, two reserved)
    "LEX",
    "001",
    LexInvalidToken,
    "Invalid Token",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "LEX",
    "002",
    LexUnclosedMultilineComment,
    "Unclosed Multiline Comment",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "LEX",
    "003",
    LexIndentationMismatch,
    "Indentation Mismatch",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "LEX",
    "004",
    LexUnclosedStringLiteral,
    "Unclosed String Literal",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    "LEX",
    "005",
    LexInvalidBinaryLiteral,
    "Invalid Binary Literal",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "LEX",
    "006",
    LexInvalidOctalLiteral,
    "Invalid Octal Literal",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "LEX",
    "007",
    LexInvalidHexLiteral,
    "Invalid Hex Literal",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "LEX",
    "008",
    LexInvalidNumberLiteral,
    "Invalid Number Literal",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "LEX",
    "009",
    LexInvalidRegexLiteral,
    "Invalid Regex Literal",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "LEX",
    "010",
    LexInvalidFormattedString,
    "Invalid Formatted String",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "LEX",
    "011",
    LexBackslashInFormatString,
    "Backslash in Format String",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "LEX",
    "012",
    LexInvalidFormattedStringExpression,
    "Invalid Formatted String Expression",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "LEX",
    "013",
    LexIntegerLiteralOverflow,
    "Integer Literal Overflow",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    // PAR — Parser (23 codes: 001-023, two reserved)
    "PAR",
    "001",
    ParUnexpectedToken,
    "Unexpected Token",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "002",
    ParUnexpectedEndOfFile,
    "Unexpected End of File",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "003",
    ParInvalidTypeDeclaration,
    "Invalid Type Declaration",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "004",
    ParInvalidLeftHandSide,
    "Invalid Left-Hand Side Expression",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "005",
    ParInvalidIntegerLiteral,
    "Invalid Integer Literal",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "006",
    ParInvalidFloatLiteral,
    "Invalid Float Literal",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "007",
    ParInvalidStringLiteral,
    "Invalid String Literal",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "008",
    ParInvalidBooleanLiteral,
    "Invalid Boolean Literal",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "009",
    ParInvalidInheritanceIdentifier,
    "Invalid Inheritance Identifier",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "010",
    ParDuplicateMatchPattern,
    "Duplicate Match Pattern",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "011",
    ParMissingMatchBranches,
    "Missing Match Branches",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "012",
    ParMissingStructMemberType,
    "Missing Struct Member Type",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "013",
    ParMissingStructMembers,
    "Missing Struct Members",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "014",
    ParMissingEnumMembers,
    "Missing Enum Members",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "015",
    ParMissingTypeExpression,
    "Missing Type Expression",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "016",
    ParMissingConstantInitializer,
    "Missing Constant Initializer",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "017",
    ParInvalidModifierCombination,
    "Invalid Modifier Combination",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "018",
    ParUnknownRuntime,
    "Unknown Runtime",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "019",
    ParUnsupportedAttributeTarget,
    "Unsupported Attribute Target",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "020",
    ParUnsupportedCStyleOperator,
    "Unsupported C-Style Operator",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "021",
    ParRecursionLimitExceeded,
    "Recursion Limit Exceeded",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "PAR",
    "022",
    ParInvalidAssignmentTarget,
    "Invalid Assignment Target",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    "PAR",
    "023",
    ParUnexpectedOperator,
    "Unexpected Operator",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    // NAM — Naming and identifiers (3 codes: 001-003)
    "NAM",
    "001",
    NamDeprecatedKernelContextIdentifier,
    "Deprecated Kernel Context Identifier",
    Severity::Warning,
    false,
    FixSafety::LocalEdit,
    "NAM",
    "002",
    NamModuleNotFound,
    "Module Not Found",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "NAM",
    "003",
    NamImportPathError,
    "Invalid Import Path",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    // IMP — Imports and module loading (3 codes: 001-003)
    "IMP",
    "001",
    ImpCircularImport,
    "Circular Import",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "IMP",
    "002",
    ImpNameConflict,
    "Imported Name Conflict",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "IMP",
    "003",
    ImpNameNotFoundInModule,
    "Name Not Found in Module",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    // TYP — Type checker (68 codes: 001-068)
    "TYP",
    "001",
    TypUndefinedVariable,
    "Undefined Variable",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    "TYP",
    "002",
    TypTypeMismatch,
    "Type Mismatch",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "003",
    TypUnknownType,
    "Unknown Type",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    "TYP",
    "004",
    TypMissingField,
    "Missing Field",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    "TYP",
    "005",
    TypMissingVariant,
    "Missing Variant",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    "TYP",
    "006",
    TypIncompatibleTypesInOperation,
    "Incompatible Types",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    "TYP",
    "007",
    TypImmutableAssignment,
    "Immutable Assignment",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    "TYP",
    "008",
    TypMissingReturnStatement,
    "Missing Return",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    "TYP",
    "009",
    TypInvalidCall,
    "Invalid Call",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    "TYP",
    "010",
    TypArityMismatch,
    "Arity Mismatch",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    "TYP",
    "011",
    TypNonExhaustiveMatchNeedsDefault,
    "Non-Exhaustive Enum Match",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "012",
    TypUnknownAttribute,
    "Unknown Attribute",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "013",
    TypAttributeNotValidOnTarget,
    "Attribute Not Valid",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "014",
    TypAttributeArgumentMissing,
    "Attribute Argument Missing",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "015",
    TypAttributeArgumentExtra,
    "Attribute Argument Extra",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "016",
    TypInvalidRegexLiteral,
    "Invalid Regex Literal",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "017",
    TypInvalidTestFunctionSignature,
    "Invalid Test Function Signature",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "018",
    TypMissingRequiredAttribute,
    "Missing Required Attribute",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "019",
    TypGpuLaunchBlockDimensionsInvalid,
    "GPU Launch Block Dimensions Invalid",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "020",
    TypGpuSliceRangeNotBounded,
    "GPU Slice Range Not Bounded",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "021",
    TypGpuFunctionHostBufferMismatch,
    "GPU Function Host Buffer Mismatch",
    Severity::Error,
    false,
    FixSafety::TargetChanging,
    "TYP",
    "022",
    TypGpuLaunchBlockSizeNotLiteral,
    "GPU Launch Block Size Not Literal",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "023",
    TypUnnecessaryDoubleNegation,
    "Unnecessary Double Negation",
    Severity::Warning,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "024",
    TypDecrementOperatorNotSupported,
    "Decrement Operator Not Supported",
    Severity::Warning,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "025",
    TypUnnecessaryOptionalDeclaration,
    "Unnecessary Optional Declaration",
    Severity::Warning,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "026",
    TypDeprecatedAttributeSpelling,
    "Deprecated Attribute Spelling",
    Severity::Warning,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "027",
    TypDeprecatedAttribute,
    "@deprecated Attribute",
    Severity::Warning,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "028",
    TypCustomError,
    "Custom Error",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    "TYP",
    "029",
    TypAtomicBufferTypeMismatch,
    "Atomic Buffer Type Mismatch",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "030",
    TypArgumentCountMismatch,
    "Argument Count Mismatch",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "031",
    TypArgumentOrderError,
    "Argument Order Error",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "032",
    TypNotCallable,
    "Not Callable",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "033",
    TypFieldNotFound,
    "Field Not Found",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "034",
    TypUndefinedName,
    "Undefined Name",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "035",
    TypNameNotVisible,
    "Name Not Visible",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "036",
    TypGenericArgumentCount,
    "Generic Argument Count Mismatch",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "037",
    TypGenericTypeStructure,
    "Invalid Generic Type Structure",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "038",
    TypEnumVariant,
    "Invalid Enum Variant",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "039",
    TypCollectionElementType,
    "Invalid Collection Element Type",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "040",
    TypIndexOperation,
    "Invalid Index Operation",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "041",
    TypSliceOperation,
    "Invalid Slice Operation",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "042",
    TypImmutabilityViolation,
    "Immutability Violation",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "043",
    TypTypeNotFound,
    "Type Not Found",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "044",
    TypTypeAlreadyDefined,
    "Type Already Defined",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "045",
    TypVariableAlreadyDefined,
    "Variable Already Defined",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    "TYP",
    "046",
    TypKeywordContextError,
    "Keyword Used in Invalid Context",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    "TYP",
    "047",
    TypClassInheritance,
    "Invalid Class Inheritance",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "048",
    TypTypeInference,
    "Type Inference Failure",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "049",
    TypSharedVariable,
    "Invalid Shared Variable",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "050",
    TypLoopControlFlow,
    "Invalid Loop Control Flow",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "051",
    TypRangeTypeMismatch,
    "Range Type Mismatch",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "052",
    TypBuiltinConstructor,
    "Invalid Builtin Constructor",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "053",
    TypVectorBuiltin,
    "Invalid Vector Builtin",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "054",
    TypFunctionSignature,
    "Invalid Function Signature",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "055",
    TypStaticMethodRestriction,
    "Static Method Restriction",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "056",
    TypClassDefinition,
    "Invalid Class Definition",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "057",
    TypTraitDefinition,
    "Invalid Trait Definition",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "058",
    TypStructDefinition,
    "Invalid Struct Definition",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "059",
    TypEnumDefinition,
    "Invalid Enum Definition",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "060",
    TypAsyncAwait,
    "Invalid Async or Await Usage",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "061",
    TypTypeInheritability,
    "Type Not Inheritable",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    "TYP",
    "062",
    TypPatternMatch,
    "Invalid Pattern Match",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "063",
    TypInvalidCast,
    "Invalid Cast",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "064",
    TypShadowingNotAllowed,
    "Shadowing Not Allowed",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "065",
    TypConstEvalArithmetic,
    "Invalid Constant Arithmetic",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "066",
    TypOutParameterMisuse,
    "Out Parameter Misuse",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "067",
    TypStringInterpolationType,
    "Type Not Valid in String Interpolation",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "TYP",
    "068",
    TypIntegerLiteralOutOfRange,
    "Integer Literal Out of Range",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    // OWN — Ownership and resource management (4 codes: 001-004)
    "OWN",
    "001",
    OwnResourceNotConsumedAtScopeExit,
    "Resource Not Consumed at Scope Exit",
    Severity::Warning,
    false,
    FixSafety::LocalEdit,
    "OWN",
    "002",
    OwnLinearVariableNotConsumed,
    "Linear Variable Not Consumed",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "OWN",
    "003",
    OwnUseOfMovedValue,
    "Use of Moved Value",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "OWN",
    "004",
    OwnUnusedValue,
    "Unused Value",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    // MIR — MIR lowering (15 codes: 001-015)
    "MIR",
    "001",
    MirUnsupportedExpression,
    "Unsupported Expression",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "MIR",
    "002",
    MirUnsupportedStatement,
    "Unsupported Statement",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "MIR",
    "003",
    MirUndefinedVariable,
    "Undefined Variable",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "MIR",
    "004",
    MirTypeNotFound,
    "Type Not Found",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "MIR",
    "005",
    MirBreakOutsideLoop,
    "Break Outside Loop",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "MIR",
    "006",
    MirContinueOutsideLoop,
    "Continue Outside Loop",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "MIR",
    "007",
    MirUnsupportedLeftHandSide,
    "Unsupported Left-Hand Side",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "MIR",
    "008",
    MirUnsupportedOperator,
    "Unsupported Operator",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "MIR",
    "009",
    MirUnsupportedRangeType,
    "Unsupported Range Type",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "MIR",
    "010",
    MirInvalidGpuLaunchArguments,
    "Invalid GPU Launch Arguments",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "MIR",
    "011",
    MirUnsupportedType,
    "Unsupported Type",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "MIR",
    "012",
    MirMissingStructField,
    "Missing Struct Field",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "MIR",
    "013",
    MirGpuLaunchMetadataMismatch,
    "GPU Launch Metadata Mismatch",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "MIR",
    "014",
    MirValidationFailed,
    "MIR Validation Failed",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "MIR",
    "015",
    MirCustomLoweringError,
    "Custom Lowering Error",
    Severity::Error,
    true,
    FixSafety::LocalEdit,
    // CG — Code generation (8 codes: 001-008)
    "CG",
    "001",
    CgTargetIsaCreationFailed,
    "Target ISA Error",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "CG",
    "002",
    CgModuleCreationFailed,
    "Module Creation Error",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "CG",
    "003",
    CgFunctionDeclarationFailed,
    "Function Declaration Error",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "CG",
    "004",
    CgFunctionDefinitionFailed,
    "Function Definition Error",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "CG",
    "005",
    CgTranslationToBackendIrFailed,
    "Translation Error",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "CG",
    "006",
    CgObjectFileEmissionFailed,
    "Emit Error",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "CG",
    "007",
    CgBackendNotSupported,
    "Backend Not Supported",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "CG",
    "008",
    CgInternalCodegenError,
    "Internal Codegen Error",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    // RT — Runtime traps and assertion failures (5 codes: 001-005)
    "RT",
    "001",
    RtDivisionByZero,
    "Division by Zero",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "RT",
    "002",
    RtRemainderByZero,
    "Remainder by Zero",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "RT",
    "003",
    RtIntegerOverflow,
    "Integer Overflow",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "RT",
    "004",
    RtInvalidOperand,
    "Invalid Operand",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    "RT",
    "005",
    RtAssertionFailed,
    "Assertion Failure",
    Severity::Error,
    false,
    FixSafety::LocalEdit,
    // TAR — Target capabilities (9 codes: 001-009)
    "TAR",
    "001",
    TarShuffleOffsetTooLarge,
    "Shuffle Offset Exceeds Subgroup Size",
    Severity::Error,
    false,
    FixSafety::TargetChanging,
    "TAR",
    "002",
    TarGpuCodeRestriction,
    "Unsupported Operation in GPU Code",
    Severity::Error,
    false,
    FixSafety::TargetChanging,
    "TAR",
    "003",
    TarGpuDivModRange,
    "GPU Division or Modulo Range",
    Severity::Error,
    false,
    FixSafety::TargetChanging,
    "TAR",
    "004",
    TarGpuBarrierControl,
    "Invalid GPU Barrier Control",
    Severity::Error,
    false,
    FixSafety::TargetChanging,
    "TAR",
    "005",
    TarGpuParallelConstruct,
    "Invalid GPU Parallel Construct",
    Severity::Error,
    false,
    FixSafety::TargetChanging,
    "TAR",
    "006",
    TarGpuResidencyViolation,
    "GPU Residency Violation",
    Severity::Error,
    false,
    FixSafety::TargetChanging,
    "TAR",
    "007",
    TarGpuTypeNotAccelerable,
    "Type Not Accelerable",
    Severity::Error,
    false,
    FixSafety::TargetChanging,
    "TAR",
    "008",
    TarGpuIncompatibleSignature,
    "GPU-Incompatible Function Signature",
    Severity::Error,
    false,
    FixSafety::TargetChanging,
    "TAR",
    "009",
    TarGpuValueOutOfRange,
    "Value Out of Range for GPU Storage",
    Severity::Error,
    false,
    FixSafety::TargetChanging,
    // BLD — Build and command-invocation (16 codes: 001-016)
    "BLD",
    "001",
    BldUnknownDiagnosticCode,
    "Unknown Diagnostic Code",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "002",
    BldRefusedRepairs,
    "Refused: Repairs Require Human Review",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "003",
    BldNonDeterministicArtifact,
    "Non-Deterministic Artifact",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "004",
    BldFunctionNotFound,
    "Function Not Found",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "005",
    BldAmbiguousFunctionName,
    "Ambiguous Function Name",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "006",
    BldAnchorTextNotFound,
    "Anchor Text Not Found",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "007",
    BldAnchorTextNotUnique,
    "Anchor Text Not Unique",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "008",
    BldInputNotReadable,
    "Input Not Readable",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "009",
    BldStaleHashMismatch,
    "Stale Hash Mismatch",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "010",
    BldSourceNotAnchorable,
    "Source Not Anchorable",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "011",
    BldEditRejected,
    "Edit Rejected: File Unchanged",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "012",
    BldMalformedEditRequest,
    "Malformed Edit Request",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "013",
    BldUnknownSkill,
    "Unknown Skill",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "014",
    BldSkillLocallyModified,
    "Refused: Skill File Locally Modified",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "015",
    BldOutputNotWritable,
    "Output Not Writable",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "016",
    BldSkillSourceMalformed,
    "Skill Source Malformed",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "017",
    BldDeclarationAlreadyExists,
    "Declaration Already Exists",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "018",
    BldFormatterNotIdempotent,
    "Formatter Not Idempotent",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
    "BLD",
    "019",
    BldFormatWouldLoseContent,
    "Formatting Would Lose Content",
    Severity::Error,
    false,
    FixSafety::RequiresHumanReview,
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_all_codes_are_unique_by_wire_string() {
        let mut seen = std::collections::HashSet::new();
        for code in DiagnosticCode::all() {
            let wire = code.as_str();
            assert!(seen.insert(wire), "duplicate: {}", wire);
        }
    }

    #[test]
    fn test_area_extraction() {
        assert_eq!(DiagnosticCode::LexInvalidToken.area(), "LEX");
        assert_eq!(DiagnosticCode::ParUnexpectedToken.area(), "PAR");
        assert_eq!(
            DiagnosticCode::NamDeprecatedKernelContextIdentifier.area(),
            "NAM"
        );
        assert_eq!(DiagnosticCode::TypUnknownAttribute.area(), "TYP");
        assert_eq!(
            DiagnosticCode::OwnResourceNotConsumedAtScopeExit.area(),
            "OWN"
        );
        assert_eq!(DiagnosticCode::MirUnsupportedExpression.area(), "MIR");
        assert_eq!(DiagnosticCode::CgTargetIsaCreationFailed.area(), "CG");
        assert_eq!(DiagnosticCode::RtDivisionByZero.area(), "RT");
        assert_eq!(DiagnosticCode::TarShuffleOffsetTooLarge.area(), "TAR");
    }

    #[test]
    fn test_severity_extraction() {
        assert_eq!(DiagnosticCode::LexInvalidToken.severity(), Severity::Error);
        assert_eq!(
            DiagnosticCode::TypUnnecessaryDoubleNegation.severity(),
            Severity::Warning
        );
        assert_eq!(
            DiagnosticCode::OwnResourceNotConsumedAtScopeExit.severity(),
            Severity::Warning
        );
    }

    #[test]
    fn test_reserved_codes() {
        assert!(DiagnosticCode::LexUnclosedStringLiteral.is_reserved());
        assert!(!DiagnosticCode::LexInvalidToken.is_reserved());
    }

    #[test]
    fn test_wire_format() {
        assert_eq!(DiagnosticCode::LexInvalidToken.as_str(), "MER_LEX_001");
        assert_eq!(DiagnosticCode::TypTypeMismatch.as_str(), "MER_TYP_002");
        assert_eq!(
            DiagnosticCode::TarShuffleOffsetTooLarge.as_str(),
            "MER_TAR_001"
        );
    }

    #[test]
    fn test_from_str() {
        assert_eq!(
            "MER_LEX_001".parse::<DiagnosticCode>().unwrap(),
            DiagnosticCode::LexInvalidToken
        );
        assert_eq!(
            "MER_TYP_027".parse::<DiagnosticCode>().unwrap(),
            DiagnosticCode::TypDeprecatedAttribute
        );
        assert!("MER_INVALID_001".parse::<DiagnosticCode>().is_err());
    }
}
