// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Viacheslav Shynkarenko

pub mod arithmetic;
pub mod array;
pub mod basic;
pub mod comparisons;
pub mod complex;
pub mod constant;
pub mod control_flow;
pub mod enums;
pub mod fstring;
pub mod function_params;
pub mod functions;
pub mod generics;
pub mod lambdas;
pub mod list;
pub mod map;
pub mod oop;
pub mod operator_traits;
pub mod option;
pub mod pattern_matching;
pub mod primitive_types;
pub mod runtime_function;
pub mod script;
pub mod set;
pub mod strings;
pub mod structs;
pub mod tuple;
pub mod type_alias;
pub mod utils;
pub mod variable;
