// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Viacheslav Shynkarenko

use super::token::Token;
use std::borrow::Cow;

/// Returns a human-readable string representation of a token for error messages.
/// Uses `Cow<'static, str>` to avoid allocations for known static strings.
pub fn token_to_string(token: &Token) -> Cow<'static, str> {
    match token {
        Token::Use => "use".into(),
        Token::Fn => "fn".into(),
        Token::Async => "async".into(),
        Token::Await => "await".into(),
        Token::Spawn => "spawn".into(),
        Token::Parallel => "parallel".into(),
        Token::Gpu => "gpu".into(),
        Token::If => "if".into(),
        Token::Unless => "unless".into(),
        Token::Else => "else".into(),
        Token::Match => "match".into(),
        Token::Default => "default".into(),
        Token::Return => "return".into(),
        Token::While => "while".into(),
        Token::Until => "until".into(),
        Token::Do => "do".into(),
        Token::For => "for".into(),
        Token::Forever => "forever".into(),
        Token::In => "in".into(),
        Token::Let => "let".into(),
        Token::Var => "var".into(),
        Token::Const => "const".into(),
        Token::Or => "or".into(),
        Token::And => "and".into(),
        Token::Not => "not".into(),
        Token::True => "true".into(),
        Token::False => "false".into(),
        Token::None => "none".into(),
        Token::From => "from".into(),
        Token::As => "as".into(),
        Token::Break => "break".into(),
        Token::Continue => "continue".into(),
        Token::Extends => "extends".into(),
        Token::Is => "is".into(),
        Token::Includes => "includes".into(),
        Token::Implements => "implements".into(),
        Token::Type => "type".into(),
        Token::Enum => "enum".into(),
        Token::Struct => "struct".into(),
        Token::Class => "class".into(),
        Token::Trait => "trait".into(),
        Token::Super => "super".into(),
        Token::Public => "public".into(),
        Token::Protected => "protected".into(),
        Token::Shared => "shared".into(),
        Token::Private => "private".into(),
        Token::System => "system".into(),
        Token::Local => "local".into(),
        Token::Abstract => "abstract".into(),
        Token::MustUse => "must_use".into(),
        Token::Out => "out".into(),
        Token::Runtime => "runtime".into(),
        Token::Intrinsic => "intrinsic".into(),

        Token::Semicolon => ";".into(),
        Token::Colon => ":".into(),
        Token::DoubleColon => "::".into(),
        Token::FatArrow => "=>".into(),
        Token::Arrow => "->".into(),
        Token::LeftArrow => "<-".into(),
        Token::Equal => "==".into(),
        Token::NotEqual => "!=".into(),
        Token::GreaterThanEqual => ">=".into(),
        Token::LessThanEqual => "<=".into(),
        Token::GreaterThan => ">".into(),
        Token::LessThan => "<".into(),
        Token::Assign => "=".into(),
        Token::AssignAdd => "+=".into(),
        Token::AssignSub => "-=".into(),
        Token::AssignMul => "*=".into(),
        Token::AssignDiv => "/=".into(),
        Token::AssignMod => "%=".into(),
        Token::Plus => "+".into(),
        Token::Increment => "++".into(),
        Token::Minus => "-".into(),
        Token::Decrement => "--".into(),
        Token::Star => "*".into(),
        Token::Slash => "/".into(),
        Token::Percent => "%".into(),
        Token::Comma => ",".into(),
        Token::Range => "..".into(),
        Token::RangeInclusive => "..=".into(),
        Token::Dot => ".".into(),
        Token::LParen => "(".into(),
        Token::RParen => ")".into(),
        Token::LBracket => "[".into(),
        Token::RBracket => "]".into(),
        Token::LBrace => "{".into(),
        Token::RBrace => "}".into(),
        Token::Pipe => "|".into(),
        Token::Ampersand => "&".into(),
        Token::Caret => "^".into(),
        Token::QuestionMark => "?".into(),
        Token::QuestionQuestion => "??".into(),
        Token::Tilde => "~".into(),

        Token::Identifier => "identifier".into(),
        Token::SingleQuotedRegex | Token::DoubleQuotedRegex => "regex literal".into(),
        Token::Regex(_) => "regular expression".into(),
        Token::SingleQuotedString | Token::DoubleQuotedString | Token::String => "string".into(),
        Token::SingleQuotedFormattedString | Token::DoubleQuotedFormattedString => {
            "formatted string".into()
        }
        Token::FormattedStringStart(_) => "start of a formatted string".into(),
        Token::FormattedStringMiddle(_) => "middle of a formatted string".into(),
        Token::FormattedStringEnd(_) => "end of a formatted string".into(),

        Token::Int => "int".into(),
        Token::Float | Token::FloatOrRange => "float".into(),
        Token::BinaryNumber => "binary number".into(),
        Token::HexNumber => "hex number".into(),
        Token::OctalNumber => "octal number".into(),
        Token::InvalidNumber => "invalid number".into(),
        Token::InvalidBinaryNumber => "invalid binary number".into(),
        Token::InvalidHexNumber => "invalid hex number".into(),
        Token::InvalidOctalNumber => "invalid octal number".into(),

        Token::InlineComment | Token::MultilineComment => "comment".into(),
        Token::Newline => "newline".into(),
        Token::Indent => "indent".into(),
        Token::Dedent => "dedent".into(),
        Token::ExpressionStatementEnd => "end of expression".into(),
        Token::Whitespace => "whitespace".into(),
        Token::Shebang => "shebang".into(),
        Token::ByteOrderMark => "byte order mark".into(),
    }
}
