// SPDX-License-Identifier: Apache-2.0
// Copyright (c) Viacheslav Shynkarenko

use super::token::Token;

/// Returns a human-readable string representation of a token for error messages.
pub fn token_to_string(token: &Token) -> String {
    match token {
        Token::Colon => ":".into(),
        Token::DoubleColon => "::".into(),
        Token::FatArrow => "=>".into(),
        Token::Arrow => "->".into(),
        Token::LeftArrow => "<-".into(),
        Token::Equal => "==".into(),
        Token::NotEqual => "!=".into(),
        Token::GreaterThanEqual => ">=".into(),
        Token::LessThanEqual => "<=".into(),
        Token::GreaterThan => ">".into(),
        Token::LessThan => "<".into(),
        Token::Assign => "=".into(),
        Token::AssignAdd => "+=".into(),
        Token::AssignSub => "-=".into(),
        Token::AssignMul => "*=".into(),
        Token::AssignDiv => "/=".into(),
        Token::AssignMod => "%=".into(),
        Token::Plus => "+".into(),
        Token::Increment => "++".into(),
        Token::Minus => "-".into(),
        Token::Decrement => "--".into(),
        Token::Star => "*".into(),
        Token::Slash => "/".into(),
        Token::Percent => "%".into(),
        Token::Comma => ",".into(),
        Token::Range => "..".into(),
        Token::RangeInclusive => "..=".into(),
        Token::Dot => ".".into(),
        Token::LParen => "(".into(),
        Token::RParen => ")".into(),
        Token::LBracket => "[".into(),
        Token::RBracket => "]".into(),
        Token::LBrace => "{".into(),
        Token::RBrace => "}".into(),
        Token::Pipe => "|".into(),
        Token::Ampersand => "&".into(),
        Token::Caret => "^".into(),
        Token::QuestionMark => "?".into(),
        Token::Tilde => "~".into(),
        Token::ExpressionStatementEnd => "end of expression".into(),
        Token::String => "string".into(),
        Token::SingleQuotedString => "string".into(),
        Token::DoubleQuotedString => "string".into(),
        Token::Regex(_) => "regular expression".into(),
        Token::FormattedStringStart(_) => "start of a formatted string".into(),
        Token::FormattedStringMiddle(_) => "middle of a formatted string".into(),
        Token::FormattedStringEnd(_) => "end of a formatted string".into(),
        _ => format!("{:?}", token).to_lowercase(),
    }
}
