// SPDX-License-Identifier: Apache-2.0
// Copyright 2017–2026 Viacheslav Shynkarenko

pub mod await_expression;
pub mod boolean;
pub mod class;
pub mod conditional_expression;
pub mod control_flow;
pub mod float;
pub mod function;
pub mod generics;
pub mod gpu_launch;
pub mod integer;
pub mod lambda;
pub mod list;
pub mod map;
pub mod match_expression;
pub mod multiple_errors;
pub mod mutability;
pub mod nullable;
pub mod result;
pub mod set;
pub mod shadowing;
pub mod shared_memory;
pub mod string;
pub mod tuple;
pub mod user_defined_types;
pub mod utils;
pub mod visibility;
